name: Deploy to ADO

on:
  [push, pull_request]

jobs:
  DeplyJob:
   name: Make call to ADO
   runs-on: ubuntu-latest
   steps:
   - name: Azure Pipelines execution
     uses: Azure/pipelines@v1
     with:
      azure-devops-project-url: https://dev.azure.com/clouduserpc4f08460/TestGitHubActions
      azure-pipeline-name: 'Rafeea1.TestGithubActions'
      azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
